r"""Référentiel de types MIME **intégré à l'exécutable** (module .py, pas une donnée).

Généré par ``outils/gen_mime_data.py`` à partir du fichier de descriptions
d'Intella et de ``mimetypes/noms_observes.txt``. PyInstaller l'embarque comme
n'importe quel module source : l'application nomme les types dès sa première
installation, sans dossier ``mimetypes`` ni import préalable.

Un fichier externe ``mimetypes\*.properties`` reste **prioritaire** sur
``DESCRIPTIONS`` (voir ``mime_catalog.load``) : une nouvelle version d'Intella
s'absorbe sans recompiler. ``OBSERVED``, lui, **fusionne** avec les noms appris
des cas lus — ce sont des constats, pas une version.

``DESCRIPTIONS`` : {nom de type: libellé}. La clé **vide** est le type
« Untyped » : ce n'est pas une scorie.
``OBSERVED`` : noms réellement écrits par Intella dans un filtre, alias compris,
que les descriptions ne couvrent pas toujours.
"""

DESCRIPTIONS = {
    "": "Untyped",
    "application/applefile": "AppleSingle File",
    "application/arj": "Arj Archive",
    "application/bat": "MS-DOS Batch File",
    "application/binhex": "BinHex Archive",
    "application/bzip": "Bzip Archive",
    "application/bzip2": "Bzip2 Archive",
    "application/compress": "UNIX Compressed Archive",
    "application/gzip": "Gzip Archive",
    "application/iff": "Interchange File Format (IFF) File",
    "application/internet-shortcut": "Internet Location (URL)",
    "application/java-archive": "Java Archive (JAR)",
    "application/json": "JSON file",
    "application/mbox": "Mbox file",
    "application/octet-stream": "Unknown Binary File",
    "application/ogg": "Ogg Vorbis Clip",
    "application/onenote": "Microsoft OneNote Document",
    "application/owl+xml": "OWL Ontology",
    "application/pdf": "PDF Document",
    "application/pgp-encrypted": "PGP Encrypted File",
    "application/pgp-signature": "PGP Signature File",
    "application/pkcs7-mime": "PKCS 7 S/MIME Encrypted Message",
    "application/pkcs7-signature": "PKCS #7 Signature",
    "application/plist+xml": "Apple XML Property List",
    "application/postscript": "PostScript Document",
    "application/presentations": "Corel Presentations Presentation",
    "application/presentations-v3": "Corel Presentations Presentation (v3)",
    "application/rdf+xml": "RDF/XML File",
    "application/riff": "RIFF Container File",
    "application/rsmf": "RSMF file",
    "application/rtf": "Rich Text Document",
    "application/stuffit": "StuffIt Archive",
    "application/stuffitx": "StuffIt X Archive",
    "application/trix": "TriX File",
    "application/unix-v7-tar": "UNIX v7 Tar Archive",
    "application/vnd.accessdata-ftk-ad1-disk-image": "AccessData Logical Image",
    "application/vnd.adobe.air-application-installer-package+zip": "AIR Rich Internet Application",
    "application/vnd.aff3-container": "AFF3 Disk Image",
    "application/vnd.aff4-container": "AFF4 Disk Image",
    "application/vnd.apple-safari-bookmark-db": "Apple Safari Bookmarks Database (SQLite)",
    "application/vnd.apple-safari-bookmark-entry": "Apple Safari Bookmark",
    "application/vnd.apple-safari-bookmarks-plist": "Apple Safari Bookmarks File (PList)",
    "application/vnd.apple-safari-history-db": "Apple Safari History File (SQLite)",
    "application/vnd.apple-safari-history-entry": "Apple Safari History Entry",
    "application/vnd.apple-safari-history-plist": "Apple Safari History File (PList)",
    "application/vnd.apple.keynote": "Apple Keynote",
    "application/vnd.apple.numbers": "Apple Numbers",
    "application/vnd.corel-draw": "CorelDRAW Drawing [3 - X3]",
    "application/vnd.debian.binary-package": "Debian Binary Package",
    "application/vnd.fdf": "Acrobat Forms Data Format",
    "application/vnd.framemaker": "FrameMaker Document",
    "application/vnd.google-chrome-bookmark-entry": "Google Chrome Bookmark Entry",
    "application/vnd.google-chrome-bookmarks": "Google Chrome Bookmarks File",
    "application/vnd.google-chrome-cache-index-entry": "Google Chrome Cache Index Entry",
    "application/vnd.google-chrome-cache-index-file": "Google Chrome Cache Index File",
    "application/vnd.google-chrome-cookies": "Google Chrome Cookies File",
    "application/vnd.google-chrome-cookies-entry": "Google Chrome Cookie Entry",
    "application/vnd.google-chrome-formhistory": "Google Chrome Form History File",
    "application/vnd.google-chrome-formhistory-entry": "Google Chrome Form History Entry",
    "application/vnd.google-chrome-history": "Google Chrome History File",
    "application/vnd.google-chrome-history-download": "Google Chrome Download",
    "application/vnd.google-chrome-history-entry": "Google Chrome History Entry",
    "application/vnd.google-chrome-history-kwsearch": "Google Chrome Keyword Search",
    "application/vnd.google-chrome-logindata": "Google Chrome Logins File",
    "application/vnd.google-chrome-logindata-entry": "Google Chrome Website Login",
    "application/vnd.hancom.hwpx": "HWPX Document",
    "application/vnd.lotus-notes": "HCL/IBM Notes Database",
    "application/vnd.lotus-notes-deletion-stub": "HCL/IBM Notes Deletion Stub",
    "application/vnd.lotus-notes-document": "HCL/IBM Notes Document",
    "application/vnd.mozilla-firefox-bookmark-entry": "Mozilla Firefox Bookmark Entry",
    "application/vnd.mozilla-firefox-cookies": "Mozilla Firefox Cookies File",
    "application/vnd.mozilla-firefox-cookies-entry": "Mozilla Firefox Cookie Entry",
    "application/vnd.mozilla-firefox-formhistory": "Mozilla Firefox Form History File",
    "application/vnd.mozilla-firefox-formhistory-entry": "Mozilla Firefox Form History Entry",
    "application/vnd.mozilla-firefox-history": "Mozilla Firefox History File",
    "application/vnd.mozilla-firefox-history-download": "Mozilla Firefox Download",
    "application/vnd.mozilla-firefox-history-entry": "Mozilla Firefox History Entry",
    "application/vnd.mozilla-firefox-input-entry": "Mozilla Firefox Typed URL",
    "application/vnd.ms-access": "Microsoft Access Database",
    "application/vnd.ms-activex-form-control": "ActiveX Form Controls",
    "application/vnd.ms-binder": "Microsoft Office Binder File",
    "application/vnd.ms-cab-compressed": "Microsoft Cabinet File",
    "application/vnd.ms-chart": "Microsoft Graph Chart",
    "application/vnd.ms-compound-file": "Unknown Office File",
    "application/vnd.ms-edb": "Microsoft ESE database",
    "application/vnd.ms-equation": "Microsoft Equation Object",
    "application/vnd.ms-ese": "Microsoft ESE file",
    "application/vnd.ms-excel": "Microsoft Excel 97-2003 Workbook",
    "application/vnd.ms-excel.addin.macroenabled.12": "Microsoft Excel 2007 Workbook (xlam)",
    "application/vnd.ms-excel.sheet.binary.macroenabled.12": "Microsoft Excel Binary Workbook",
    "application/vnd.ms-excel.sheet.macroenabled.12": "Microsoft Excel 2007 Workbook (xlsm)",
    "application/vnd.ms-excel.template.macroenabled.12": "Microsoft Excel 2007 Workbook (xltm)",
    "application/vnd.ms-excel.v2": "Microsoft Excel 2.0 Workbook",
    "application/vnd.ms-excel.v3": "Microsoft Excel 3.0 Workbook",
    "application/vnd.ms-excel.v4": "Microsoft Excel 4.0 Workbook",
    "application/vnd.ms-exchange-edb": "Microsoft Exchange EDB File",
    "application/vnd.ms-exchange-stm": "Microsoft Exchange STM File",
    "application/vnd.ms-ole2-container": "OLE 2.0 Container",
    "application/vnd.ms-outlook": "Microsoft Outlook MSG File",
    "application/vnd.ms-outlook-note": "Microsoft Outlook MSG File",
    "application/vnd.ms-outlook-pst": "Microsoft Outlook PST File",
    "application/vnd.ms-outlookexpress": "Microsoft Outlook Express DBX File",
    "application/vnd.ms-pki.seccat": "Microsoft Security Catalog File",
    "application/vnd.ms-powerpoint": "Microsoft PowerPoint 97-2003 Presentation",
    "application/vnd.ms-powerpoint.addin.macroenabled.12": "Microsoft PowerPoint 2007 Presentation (ppam)",
    "application/vnd.ms-powerpoint.presentation.macroenabled.12": "Microsoft PowerPoint 2007 Presentation (pptm)",
    "application/vnd.ms-powerpoint.slideshow.macroenabled.12": "Microsoft PowerPoint 2007 Presentation (ppsm)",
    "application/vnd.ms-powerpoint.template.macroenabled.12": "Microsoft PowerPoint 2007 Presentation (potm)",
    "application/vnd.ms-project": "Microsoft Project File",
    "application/vnd.ms-publisher": "Microsoft Publisher Document",
    "application/vnd.ms-registry": "Windows Registry File",
    "application/vnd.ms-registry-key": "Windows Registry Key",
    "application/vnd.ms-sdb": "Windows Compatibility Solution Database",
    "application/vnd.ms-tnef": "Microsoft Outlook TNEF Attachment File",
    "application/vnd.ms-virtualpc-disk-image": "Microsoft Virtual Hard Disk Image",
    "application/vnd.ms-virtualpc-disk-image-v2": "Microsoft Virtual Hard Disk Image v2",
    "application/vnd.ms-visio.drawing.macroenabled.main+xml": "Microsoft Visio 2007 Macro-Enabled Diagram",
    "application/vnd.ms-visio.drawing.main+xml": "Microsoft Visio 2007 Diagram",
    "application/vnd.ms-visio.stencil.macroenabled.main+xml": "Microsoft Visio 2007 Macro-Enabled Stencil",
    "application/vnd.ms-visio.stencil.main+xml": "Microsoft Visio 2007 Stencil",
    "application/vnd.ms-visio.template.macroenabled.main+xml": "Microsoft Visio 2007 Macro-Enabled Template",
    "application/vnd.ms-visio.template.main+xml": "Microsoft Visio 2007 Template",
    "application/vnd.ms-windows-event-log": "Windows Event Log",
    "application/vnd.ms-windows-ie-cookies-entry": "Internet Explorer Cookie Entry",
    "application/vnd.ms-windows-ie-recovery-store": "Internet Explorer Crash Recovery Store",
    "application/vnd.ms-windows-installer-package": "Windows Installer Package",
    "application/vnd.ms-windows-installer-patch": "Windows Installer Patch",
    "application/vnd.ms-windows-installer-transform": "Windows Installer Transform",
    "application/vnd.ms-windows-internet-bookmark": "Internet Explorer Bookmark",
    "application/vnd.ms-windows-internet-history-download": "Internet Explorer Download",
    "application/vnd.ms-windows-internet-history-entry": "Internet Explorer History Entry",
    "application/vnd.ms-windows-internet-typed-url": "Internet Explorer Typed URL",
    "application/vnd.ms-windows-search": "Windows Search database",
    "application/vnd.ms-windows-urlcache": "Internet Explorer History File",
    "application/vnd.ms-windows-webcache": "Internet Explorer History File (ESE DB)",
    "application/vnd.ms-windows-xml-event-log": "Windows XML Event Log",
    "application/vnd.ms-windows-xml-event-log-entry": "Windows XML Event Log Entry",
    "application/vnd.ms-word": "Microsoft Word 97-2003 Document",
    "application/vnd.ms-word.document.macroenabled.12": "Microsoft Word 2007 Document (docm)",
    "application/vnd.ms-word.template.macroenabled.12": "Microsoft Word 2007 Document (dotm)",
    "application/vnd.ms-works": "Microsoft Works Document",
    "application/vnd.ms-xpsdocument": "XPS Document",
    "application/vnd.oasis.opendocument.chart": "OpenDocument Chart",
    "application/vnd.oasis.opendocument.chart-template": "OpenDocument Chart Template",
    "application/vnd.oasis.opendocument.database": "OpenDocument Database",
    "application/vnd.oasis.opendocument.formula": "OpenDocument Formula",
    "application/vnd.oasis.opendocument.formula-template": "OpenDocument Formula Template",
    "application/vnd.oasis.opendocument.graphics": "OpenDocument Drawing",
    "application/vnd.oasis.opendocument.graphics-template": "OpenDocument Drawing Template",
    "application/vnd.oasis.opendocument.image": "OpenDocument Image",
    "application/vnd.oasis.opendocument.image-template": "OpenDocument Image Template",
    "application/vnd.oasis.opendocument.presentation": "OpenDocument Presentation",
    "application/vnd.oasis.opendocument.presentation-template": "OpenDocument Presentation Template",
    "application/vnd.oasis.opendocument.spreadsheet": "OpenDocument Spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet-template": "OpenDocument Spreadsheet Template",
    "application/vnd.oasis.opendocument.text": "OpenDocument Text",
    "application/vnd.oasis.opendocument.text-master": "OpenDocument Master Document",
    "application/vnd.oasis.opendocument.text-template": "OpenDocument Text Template",
    "application/vnd.oasis.opendocument.text-web": "OpenDocument Web Page Template",
    "application/vnd.openxmlformats-officedocument": "Unknown Microsoft Office 2007 Document",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "Microsoft PowerPoint 2007 Presentation (pptx)",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "Microsoft PowerPoint 2007 Presentation (ppsx)",
    "application/vnd.openxmlformats-officedocument.presentationml.template": "Microsoft PowerPoint 2007 Presentation (potx)",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "Microsoft Excel 2007 Workbook (xlsx)",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "Microsoft Excel 2007 Workbook (xltx)",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "Microsoft Word 2007 Document (docx)",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "Microsoft Word 2007 Document (dotx)",
    "application/vnd.stardivision.calc": "StarOffice Spreadsheet",
    "application/vnd.stardivision.chart": "StarOffice Chart",
    "application/vnd.stardivision.draw": "StarOffice Drawing",
    "application/vnd.stardivision.impress": "StarOffice Presentation",
    "application/vnd.stardivision.impress-packed": "StarOffice Packed Presentation",
    "application/vnd.stardivision.mail": "StarOffice Mail File",
    "application/vnd.stardivision.math": "StarOffice Math File",
    "application/vnd.stardivision.writer": "StarOffice Document",
    "application/vnd.stardivision.writer-global": "StarOffice Global Document",
    "application/vnd.sun.xml.calc": "OpenOffice Spreadsheet",
    "application/vnd.sun.xml.calc.template": "OpenOffice Spreadsheet Template",
    "application/vnd.sun.xml.draw": "OpenOffice Drawing",
    "application/vnd.sun.xml.draw.template": "OpenOffice Drawing Template",
    "application/vnd.sun.xml.impress": "OpenOffice Presentation",
    "application/vnd.sun.xml.impress.template": "OpenOffice Presentation Template",
    "application/vnd.sun.xml.math": "OpenOffice Math File",
    "application/vnd.sun.xml.writer": "OpenOffice Document",
    "application/vnd.sun.xml.writer.template": "OpenOffice Document Template",
    "application/vnd.tcpdump.pcap": "Network packet capture",
    "application/vnd.visio": "Microsoft Visio 97-2003 Diagram",
    "application/vnd.vmware-vmdk-disk-image": "VMware Disk Image",
    "application/vnd.vound.folder": "Folder",
    "application/vnd.vound.symlink": "Symbolic Link",
    "application/vnd.wordperfect": "WordPerfect Document",
    "application/wb2": "Lotus 1-2-3/Quattro Pro Spreadsheet",
    "application/winhlp": "Windows Help File",
    "application/wps-office.dps": "WPS Office Presentation File",
    "application/wps-office.et": "WPS Office Spreadsheets File",
    "application/wps-office.wps": "WPS Office Writer File",
    "application/x-123": "Lotus 1-2-3 Spreadsheet",
    "application/x-7z-compressed": "7-Zip Archive",
    "application/x-adobe-indesign": "Adobe InDesign Document",
    "application/x-alz-compressed": "ALZip Archive",
    "application/x-apple-account-database": "Apple Account Database",
    "application/x-apple-address-book-database": "Apple Address Book Database",
    "application/x-apple-calendar-database": "Apple Calendar Database",
    "application/x-apple-call-history-database": "Apple Call History Database",
    "application/x-apple-notes-database": "Apple Notes Database",
    "application/x-applescript": "AppleScript File",
    "application/x-axcrypt": "AxCrypt Encrypted File",
    "application/x-bash": "BASH Shell Script",
    "application/x-bitcoin-blockchain": "Bitcoin Blockchain",
    "application/x-bitcoin-wallet": "Bitcoin Wallet",
    "application/x-bitlocker-image": "BitLocker image",
    "application/x-bitlocker-togo-image": "BitLocker TO GO image",
    "application/x-bplist": "Apple Binary Property List",
    "application/x-cpio": "CPIO Archive",
    "application/x-csh": "CSH Shell Script",
    "application/x-dogecoin-blockchain": "Dogecoin Blockchain",
    "application/x-dogecoin-wallet": "Dogecoin Wallet",
    "application/x-emlxpart": "EMLX Email Message Part",
    "application/x-empty": "Empty file",
    "application/x-encase-ewf-image": "EnCase Disk Image",
    "application/x-encase-ewf-image-v2": "EnCase Disk Image (Version 2)",
    "application/x-encase-logical-image": "EnCase Logical Evidence File",
    "application/x-encase-logical-image-v2": "EnCase Logical Evidence File (Version 2)",
    "application/x-font-otf": "OpenType Font",
    "application/x-font-ttf": "TrueType Font",
    "application/x-foxmail": "FoxMail Mailbox",
    "application/x-gtar": "GNU Tar Archive",
    "application/x-harvard-graphics": "Harvard Graphics Document",
    "application/x-hwp": "HWP Document",
    "application/x-hwp-v3": "HWP Document V3",
    "application/x-imessage-db": "iMessage Database",
    "application/x-installshield-compressedfile": "InstallShield Compressed File",
    "application/x-intella-activity": "Activity",
    "application/x-intella-aff-disk-image": "Advanced Forensics Format Disk Image",
    "application/x-intella-android-conversation-xml": "Android Chat Conversation",
    "application/x-intella-android-logical-acquisition": "Android Logical Acquisition",
    "application/x-intella-apfs-partition": "APFS partition",
    "application/x-intella-app-account": "Application Account",
    "application/x-intella-app-usage": "Application Usage",
    "application/x-intella-apple-dmg-compressed-image": "Apple DMG compressed image",
    "application/x-intella-apple-dmg-encrypted-v1-image": "Apple Encrypted Disk Image (Version 1)",
    "application/x-intella-apple-dmg-encrypted-v2-image": "Apple Encrypted Disk Image (Version 2)",
    "application/x-intella-apple-dmg-image": "Apple DMG image",
    "application/x-intella-apple-mail": "Apple Mail",
    "application/x-intella-autofill-entry": "Autofill Entry",
    "application/x-intella-automatic-jump-list": "Jump List (Automatic)",
    "application/x-intella-aws-s3-account": "AWS S3 Account",
    "application/x-intella-aws-s3-bucket": "AWS S3 Bucket",
    "application/x-intella-bam-cache-entry": "Launched Program (BAM Cache)",
    "application/x-intella-blackberry-message": "Blackberry Message",
    "application/x-intella-bloomberg-conversation-xml": "Bloomberg Conversation",
    "application/x-intella-bloomberg-plain-text-dump": "Bloomberg Plain Text Dump",
    "application/x-intella-bloomberg-xml-dump": "Bloomberg XML Dump",
    "application/x-intella-bluetooth-connection": "Bluetooth Connection",
    "application/x-intella-bookmark": "Bookmark",
    "application/x-intella-boot-sector-file": "Boot Sector File",
    "application/x-intella-browser-cache": "Web Browser Cache",
    "application/x-intella-calendar-entry": "Calendar Entry",
    "application/x-intella-carved-string": "Carved String",
    "application/x-intella-cell-connection": "Cell Connection",
    "application/x-intella-cellebrite-conversation-xml": "Cellebrite Conversation",
    "application/x-intella-cellebrite-file": "Cellebrite Cellphone Extraction",
    "application/x-intella-cellebrite-ufdr-report-file": "Cellebrite UFDR Report File",
    "application/x-intella-cellebrite-xml-report-file": "Cellebrite XML Report File",
    "application/x-intella-cellphone-contact": "Contact (from cellphone)",
    "application/x-intella-cellphone-event": "Cellphone Event",
    "application/x-intella-cellphone-recording": "Cellphone Recording",
    "application/x-intella-cellphone-report": "Cellphone Report",
    "application/x-intella-chat-message": "Chat Message (Legacy)",
    "application/x-intella-chat-message-xml": "Chat Message",
    "application/x-intella-chat-message-xml-reaction": "Chat Message Reaction",
    "application/x-intella-comm-stat-entry": "Communication Statistics Entry",
    "application/x-intella-contact": "Contact (from PST)",
    "application/x-intella-conversation": "Chat Conversation (Legacy)",
    "application/x-intella-conversation-event": "Conversation Event",
    "application/x-intella-conversation-root": "Conversations Root",
    "application/x-intella-cookie": "Cookie",
    "application/x-intella-custom-jump-list": "Jump List (Custom)",
    "application/x-intella-dd-disk-image": "Raw Disk Image",
    "application/x-intella-device-acquisition": "Intella Device Acquisition",
    "application/x-intella-dictionary-word": "Dictionary Word",
    "application/x-intella-dropbox-account": "Dropbox Account",
    "application/x-intella-exfat-partition": "exFAT partition",
    "application/x-intella-fat16-partition": "FAT16 partition",
    "application/x-intella-fax": "Fax",
    "application/x-intella-file-message": "File Message",
    "application/x-intella-for-mac-olk14-mailbox": "Outlook for 'Mac' OLk14 mailbox",
    "application/x-intella-for-mac-olk15-mailbox": "Outlook for 'Mac' profile folder",
    "application/x-intella-gmail-account": "GMail Account",
    "application/x-intella-google-account": "Google Account",
    "application/x-intella-google-calendar": "Google Calendar",
    "application/x-intella-google-chat": "Google Chat",
    "application/x-intella-google-chat-conversation-xml": "Google Chat Conversation",
    "application/x-intella-google-chat-space": "Google Space",
    "application/x-intella-google-contacts": "Google Contacts",
    "application/x-intella-google-drive": "Google Drive",
    "application/x-intella-google-gmail": "Gmail",
    "application/x-intella-google-meet": "Google Meet",
    "application/x-intella-google-meet-conference": "Google Meet Conference",
    "application/x-intella-google-meet-participant-session": "Google Meet Participant Session",
    "application/x-intella-google-takeout-export": "Google Takeout",
    "application/x-intella-gps-location": "GPS Location",
    "application/x-intella-gpt-partition": "GPT partition",
    "application/x-intella-hfs-partition": "HFS partition",
    "application/x-intella-history-entry": "History Entry",
    "application/x-intella-hotmail-dump": "Hotmail Search Warrant Result",
    "application/x-intella-icloud-account": "iCloud Account",
    "application/x-intella-icloud-device": "iCloud Device",
    "application/x-intella-imap-connection": "IMAP Connection",
    "application/x-intella-imessage-conversation-xml": "iMessage Conversation",
    "application/x-intella-installed-application": "Installed Application",
    "application/x-intella-iphone-message": "iMessage",
    "application/x-intella-itunes-backup": "iTunes Backup",
    "application/x-intella-itunes-backup-iphone-info": "Device Information",
    "application/x-intella-itunes-backup-voicemail": "Voicemail",
    "application/x-intella-itunes-conversation-xml": "ITunes Conversation",
    "application/x-intella-itunes-encrypted-backup": "Encrypted iTunes Backup",
    "application/x-intella-journey": "Journey",
    "application/x-intella-key-evidence": "Key Evidence",
    "application/x-intella-keyboard-cache": "Keyboard Cache",
    "application/x-intella-load-file": "Load File",
    "application/x-intella-local-disk": "Local disk",
    "application/x-intella-log-entry": "System Log Entry",
    "application/x-intella-mbr-partition": "MBR partition",
    "application/x-intella-message-status-update": "Status Update Message",
    "application/x-intella-mms-message": "MMS Message",
    "application/x-intella-ms-teams-account": "Microsoft Teams Account",
    "application/x-intella-ms-teams-channel": "Microsoft Teams Channel",
    "application/x-intella-ms-teams-conversation": "Microsoft Teams Conversation (Legacy)",
    "application/x-intella-ms-teams-conversation-xml": "Microsoft Teams Conversation",
    "application/x-intella-ms-teams-message": "Microsoft Teams Message",
    "application/x-intella-net-adapter": "Network Adapter",
    "application/x-intella-net-connection": "Network Connection",
    "application/x-intella-note": "Note",
    "application/x-intella-notification": "Notification",
    "application/x-intella-office365-account": "Microsoft 365 Account",
    "application/x-intella-office365-connection": "Microsoft 365 Connection",
    "application/x-intella-olk14category": "OLK14 Category File",
    "application/x-intella-olk14contacts": "OLK14 Contact File",
    "application/x-intella-olk14dbheader": "OLK14 Database Header File",
    "application/x-intella-olk14event": "OLK14 Event File",
    "application/x-intella-olk14folder": "OLK14 Folder File",
    "application/x-intella-olk14message": "OLK14 Message File",
    "application/x-intella-olk14msgattachment": "OLK14 Message Attachment File",
    "application/x-intella-olk14msgsource": "OLK14 Message Source File",
    "application/x-intella-olk14note": "OLK14 Note File",
    "application/x-intella-olk14preferences": "OLK14 Preferences File",
    "application/x-intella-olk14recent": "OLK14 Recent File",
    "application/x-intella-olk14schedule": "OLK14 Schedule File",
    "application/x-intella-olk14search": "OLK14 Search File",
    "application/x-intella-olk14signatures": "OLK14 Signature File",
    "application/x-intella-olk15": "Unknown olk15 file",
    "application/x-intella-olk15calattachment": "olk15 calendar attachment file",
    "application/x-intella-olk15category": "olk15 category file",
    "application/x-intella-olk15contact": "olk15 contact file",
    "application/x-intella-olk15event": "olk15 event file",
    "application/x-intella-olk15fold": "olk15 fold file",
    "application/x-intella-olk15folder": "olk15 folder file",
    "application/x-intella-olk15image": "olk15 image file",
    "application/x-intella-olk15imapsyncmap": "olk15 imap sync map file",
    "application/x-intella-olk15mailaccount": "olk15 mail account file",
    "application/x-intella-olk15main": "olk15 main file",
    "application/x-intella-olk15message": "olk15 message file",
    "application/x-intella-olk15msgattachment": "olk15 message attachment file",
    "application/x-intella-olk15msgsource": "olk15 message source file",
    "application/x-intella-olk15note": "olk15 note file",
    "application/x-intella-olk15recentaddresses": "olk15 recent addresses file",
    "application/x-intella-olk15search": "olk15 search file",
    "application/x-intella-olk15signature": "olk15 signature file",
    "application/x-intella-olk15task": "olk15 task file",
    "application/x-intella-onedrive-account": "OneDrive Account",
    "application/x-intella-operating-system-information": "Operating System Information",
    "application/x-intella-outlook-account": "Outlook Account",
    "application/x-intella-outlook-distribution-list": "Microsoft Outlook Distribution List",
    "application/x-intella-outlook-for-mac": "Microsoft Outlook for Mac Archive",
    "application/x-intella-outlook-ipm-DistList": "Microsoft Outlook Distribution List",
    "application/x-intella-outlook-ipm-SkypeTeams-Message": "Microsoft Teams Message (PST)",
    "application/x-intella-outlook-sharing-message": "Microsoft Outlook Sharing Message",
    "application/x-intella-oxygen-conversation-xml": "Oxygen Conversation",
    "application/x-intella-oxygen-file": "Oxygen Cellphone Extraction",
    "application/x-intella-oxygen-xml-report-file": "Oxygen XML Report File",
    "application/x-intella-packet-data": "Packet Data",
    "application/x-intella-password": "Password",
    "application/x-intella-phone-call": "Phone Call",
    "application/x-intella-phone-conversation": "SMS/MMS Conversation (Legacy)",
    "application/x-intella-pidgin-accounts-file": "Pidgin Accounts File",
    "application/x-intella-pidgin-html-conversation": "Pidgin HTML Conversation (Legacy)",
    "application/x-intella-pidgin-html-conversation-xml": "Pidgin HTML Conversation",
    "application/x-intella-pidgin-html-dump": "Pidgin HTML Dump",
    "application/x-intella-pidgin-plain-text-conversation": "Pidgin Plain Text Conversation (Legacy)",
    "application/x-intella-pidgin-plain-text-conversation-xml": "Pidgin Plain Text Conversation",
    "application/x-intella-pidgin-plain-text-dump": "Pidgin Plain Text Dump",
    "application/x-intella-powering-event": "Powering Event",
    "application/x-intella-prefetch-file": "Windows Prefetch File",
    "application/x-intella-prefetch-file-entry": "Launched Program (Prefetch)",
    "application/x-intella-raw-disk": "RAW partition",
    "application/x-intella-recent-apps-entry": "Launched Program (RecentApps)",
    "application/x-intella-recent-items-entry": "Recently Accessed File (RecentApps)",
    "application/x-intella-recently-used-file": "Recently Accessed File",
    "application/x-intella-rsmf-conversation-xml": "RSMF Conversation",
    "application/x-intella-rss-feed": "RSS Feed",
    "application/x-intella-run-mru-entry": "Launched Program (RunMRU)",
    "application/x-intella-sametime-dump": "IBM Sametime Dump",
    "application/x-intella-sametime-dump-xml": "IBM Sametime Dump XML",
    "application/x-intella-search-entry": "Search Entry",
    "application/x-intella-sharepoint-account": "SharePoint Account",
    "application/x-intella-sharepoint-discussion-board": "SharePoint Discussion Board",
    "application/x-intella-sharepoint-doc-library": "SharePoint Document Library",
    "application/x-intella-sharepoint-newsfeed": "SharePoint NewsFeed",
    "application/x-intella-sharepoint-post": "SharePoint Post",
    "application/x-intella-sharepoint-site": "SharePoint Site",
    "application/x-intella-skype-conversation": "Skype Conversation (Legacy)",
    "application/x-intella-skype-conversation-xml": "Skype DB Conversation",
    "application/x-intella-skype-message": "Skype Message",
    "application/x-intella-slack": "Slack export",
    "application/x-intella-slack-activity-log": "Activity log",
    "application/x-intella-slack-conversation": "Slack conversation (Legacy)",
    "application/x-intella-slack-conversation-thread": "Slack conversation thread (Legacy)",
    "application/x-intella-slack-conversation-xml": "Slack conversation",
    "application/x-intella-slack-conversations": "Slack conversations",
    "application/x-intella-slack-direct-m-channel": "Slack direct messages channel",
    "application/x-intella-slack-entry": "Slack entry",
    "application/x-intella-slack-file": "Slack attached file",
    "application/x-intella-slack-group-m-channel": "Slack group channel",
    "application/x-intella-slack-log": "Slack log",
    "application/x-intella-slack-message": "Slack message",
    "application/x-intella-slack-mp-direct-m-channel": "Slack multi party direct message channel",
    "application/x-intella-slack-public-channel": "Slack public channel",
    "application/x-intella-sms-message": "SMS Message",
    "application/x-intella-speed-dial": "Speed Dial",
    "application/x-intella-sqlite-table-records": "SQLite 3 Database Table Records",
    "application/x-intella-startup-program": "Startup Program",
    "application/x-intella-task": "Task",
    "application/x-intella-task-request": "Task Request",
    "application/x-intella-time-zone-information": "Time Zone",
    "application/x-intella-timeline-entry": "Timeline Entry",
    "application/x-intella-unknown-cellphone-item": "Unknown Cellphone Item",
    "application/x-intella-usb-storage-device": "USB Storage Device",
    "application/x-intella-user-account": "User Account",
    "application/x-intella-user-account-login": "User Logged In",
    "application/x-intella-user-account-logout": "User Logged Out",
    "application/x-intella-user-assist": "Launched Program (User Assist)",
    "application/x-intella-voicemail": "Voice Mail",
    "application/x-intella-w4-case": "Vound W4 Case",
    "application/x-intella-web-browser-download": "Web Browser Download",
    "application/x-intella-whatsapp-conversation-xml": "WhatsApp Chat Conversation",
    "application/x-intella-wifi-connection": "WiFi Connection",
    "application/x-intella-windows-10-timeline-db": "Windows 10 Timeline Database",
    "application/x-intella-windows-10-timeline-entry": "Windows 10 Timeline Entry",
    "application/x-intella-windows-push-notification-db": "Windows Push Notification Database",
    "application/x-intella-windows-push-notification-entry": "Windows Push Notification",
    "application/x-intella-windows-registry-artifacts": "Windows Registry Artifacts",
    "application/x-intella-windows-shellbag": "Windows ShellBag",
    "application/x-intella-windows10mail-backup": "Windows 10 Mail",
    "application/x-intella-xry-conversation-xml": "XRY Conversation",
    "application/x-intella-xry-file": "XRY Cellphone Extraction",
    "application/x-intella-xry-xml-report-file": "XRY XML Report File",
    "application/x-intella-xwfs2-disk": "X-Ways disk image",
    "application/x-iso-base-media": "ISO base media file",
    "application/x-iso9660-image": "ISO image",
    "application/x-java-class": "Java Class File",
    "application/x-java-enterprisearchive": "Java Enterprise Application Archive (EAR)",
    "application/x-java-webarchive": "Java Web Application Archive (WAR)",
    "application/x-ksh": "KSH Shell Script",
    "application/x-litecoin-blockchain": "Litecoin BLockchain",
    "application/x-md5": "MD5 Checksum File",
    "application/x-microsoft-rpmsg-message": "Restricted Permission Message",
    "application/x-mimearchive": "Web Archive",
    "application/x-ms-dos-executable": "MS-DOS/Windows Executable",
    "application/x-ms-scr": "Windows Screen Saver",
    "application/x-ms-shortcut": "Windows Shortcut File",
    "application/x-ms-wmz": "Windows Media Compressed Skin File",
    "application/x-multibit-blockchain": "Multibit Blockchain",
    "application/x-multibit-classic-wallet": "Multibit Classic Wallet",
    "application/x-multibit-hd-wallet": "Multibit HD Wallet",
    "application/x-quattropro": "Quattro Pro Spreadsheet",
    "application/x-rar-compressed": "Rar Archive",
    "application/x-rar-compressed-v5": "Rar5 Archive",
    "application/x-redhat-package-manager": "RPM Package",
    "application/x-sh": "SH Shell Script",
    "application/x-sha": "SHA(n) Checksum File",
    "application/x-shockwave-flash": "Flash File",
    "application/x-sicky-notes-db": "Sticky Notes Database",
    "application/x-sicky-notes-message": "Sticky Note",
    "application/x-slk": "Symbolic Link spreadsheet",
    "application/x-sqlite2": "SQLite 2 Database",
    "application/x-sqlite3": "SQLite 3 Database",
    "application/x-sqlite3-skype": "Skype Database",
    "application/x-sqlite3-skype-11x-12x": "Skype 11.x-12.x Database",
    "application/x-sqlite3-skype-14x": "Skype 14x Database",
    "application/x-sqlite3-skype-8x": "Skype 8.x Database",
    "application/x-tar": "UNIX Standard Tar Archive",
    "application/x-tsh": "TSH Shell Script",
    "application/x-turtle": "Turtle File",
    "application/x-vnd.corel.zcf.draw.document+zip": "CorelDRAW Drawing [X4 - X7]",
    "application/x-webarchive": "Safari WebArchive",
    "application/x-whatsapp-db": "WhatsApp Database",
    "application/x-wim": "Windows Imaging File",
    "application/x-xz": "XZ Archive",
    "application/xhtml+xml": "XHTML Document",
    "application/xml": "XML Document",
    "application/xslt+xml": "XSLT Style Sheet",
    "application/zip": "Zip Archive",
    "application/zst": "Zstandard Archive",
    "audio/8svx": "8-Bit Sampled Voice",
    "audio/aiff": "AIFF Audio Clip",
    "audio/amr": "AMR Audio Clip",
    "audio/amr-wb": "AMR Wideband Audio Clip",
    "audio/flac": "FLAC Audio Clip",
    "audio/midi": "MIDI Audio Clip",
    "audio/midi+riff": "RIFF-based MIDI Audio Clip",
    "audio/mp3": "MP3 Audio Clip",
    "audio/mp4": "MPEG-4 Audio File",
    "audio/wave": "WAV Audio Clip",
    "audio/x-aifc": "Compressed AIFF Audio Clip",
    "audio/x-ms-wax": "Windows Media Audio Redirector",
    "audio/x-ms-wma": "Windows Media Audio Clip",
    "category/accounts": "Accounts",
    "category/apple_plist": "Apple Property List (PList)",
    "category/archives": "Archives",
    "category/audio": "Audio",
    "category/aws-s3": "AWS S3",
    "category/browser_bookmarks": "Bookmarks",
    "category/browser_cookies": "Cookies",
    "category/browser_downloads": "Downloads",
    "category/browser_form_history": "Form History",
    "category/browser_history": "History",
    "category/browser_logins": "Logins",
    "category/cell_phone": "Cell phone",
    "category/chat": "Chat",
    "category/chat_conversations": "Chat Conversations",
    "category/chat_messages": "Chat Messages",
    "category/cloud_service": "Cloud service",
    "category/communication": "Communication",
    "category/contacts": "Contacts",
    "category/containers": "Containers",
    "category/corel_draw": "CorelDRAW Drawing",
    "category/crypto_currency": "Crypto Currency",
    "category/databases": "Databases",
    "category/disk_images": "Disk images",
    "category/documents": "Documents",
    "category/dropbox": "Dropbox",
    "category/email": "E-mail",
    "category/email_containers": "E-mail containers",
    "category/email_messages": "E-mail Messages",
    "category/executables": "Executables",
    "category/forensic_containers": "Forensic containers",
    "category/formulas": "Formulas",
    "category/gmail": "Gmail (legacy)",
    "category/google": "Google",
    "category/graphics": "Graphics",
    "category/hangul_document": "Hangul document",
    "category/icloud": "iCloud",
    "category/images": "Images",
    "category/java_archives": "Java Archive",
    "category/launched_programs": "Launched Programs",
    "category/media": "Media",
    "category/microsoft_excel": "Microsoft Excel Workbook",
    "category/microsoft_powerpoint": "Microsoft PowerPoint Presentation",
    "category/microsoft_visio": "Microsoft Visio Diagram",
    "category/microsoft_word": "Microsoft Word Document",
    "category/office365": "Microsoft 365",
    "category/office_openxml_excel": "Microsoft Excel 2007 Workbook",
    "category/office_openxml_powerpoint": "Microsoft PowerPoint 2007 Presentation",
    "category/office_openxml_word": "Microsoft Word 2007 Document",
    "category/olk14": "Outlook for Mac (OLK14, 2011)",
    "category/olk15": "Outlook for Mac (OLK15, 2016+)",
    "category/other_communications": "Other communications",
    "category/other_documents": "Other documents",
    "category/other_media": "Other Media",
    "category/others": "Others",
    "category/phoneBackups": "Phone Backups",
    "category/pidgin_chat": "Pidgin Conversation",
    "category/presentations": "Presentations",
    "category/rar_archives": "Rar Archives",
    "category/recently_accessed_files": "Recently Accessed Files",
    "category/root": "All items",
    "category/scheduling": "Scheduling",
    "category/security_and_integrity": "Security & integrity",
    "category/sharepoint": "SharePoint",
    "category/source_code": "Source code",
    "category/spreadsheets": "Spreadsheets",
    "category/sqlite": "SQLite",
    "category/system": "System",
    "category/tar_archives": "Tar Archive",
    "category/unix_shell_scripts": "Unix shell script",
    "category/unknown": "Unknown",
    "category/user_activity": "User activity",
    "category/user_sessions": "User Sessions",
    "category/video": "Video",
    "category/voice": "Voice",
    "category/windows_registry": "Windows registry",
    "category/word_processing": "Word processing",
    "category/wrappers": "Wrappers",
    "category/www": "WWW",
    "image/bmp": "BMP Image",
    "image/cgm": "CGM Image",
    "image/dng": "Digital Negative Image",
    "image/gif": "GIF Image",
    "image/heic": "HEIC Image",
    "image/heic-sequence": "HEIC Image Sequence",
    "image/heif": "HEIF Image",
    "image/heif-sequence": "HEIF Image Sequence",
    "image/icns": "Apple Icon",
    "image/ilbm": "InterLeaved BitMap",
    "image/jbig2": "JBIG2 Image",
    "image/jp2": "JPEG 2000 Base Still Image",
    "image/jpeg": "JPEG Image",
    "image/jpeg2000": "JPEG 2000 Image",
    "image/jpeg2000-codestream": "JPEG 2000 codestream",
    "image/jpm": "JPEG 2000 Compound Image",
    "image/jpx": "JPEG 2000 Extended Still Image",
    "image/notesbitmap": "HCL/IBM Notes Bitmap",
    "image/pict": "PICT image",
    "image/png": "PNG Image",
    "image/svg+xml": "SVG Image",
    "image/tiff": "TIFF Image",
    "image/vnd.adobe.photoshop": "Adobe Photoshop Image",
    "image/vnd.djvu": "DjVu Image",
    "image/vnd.ms-modi": "Microsoft Document Imaging File",
    "image/vnd.radiance": "Radiance High Dynamic Range Image",
    "image/vnd.zbrush.pcx": "ZSoft PCX Image",
    "image/webp": "WebP Image",
    "image/x-dwf": "AutoCAD DWF File",
    "image/x-dwg": "AutoCAD DWG File",
    "image/x-dxf": "AutoCAD DXF File",
    "image/x-emf": "EMF Image",
    "image/x-icon": "Icon",
    "image/x-itunes-albumartwork": "iTunes Album Artwork",
    "image/x-paintshoppro": "Paint Shop Pro Image",
    "image/x-pcx": "PCX Image",
    "image/x-portable-bitmap": "Portable Bitmap Image",
    "image/x-portable-greymap": "Portable Greymap Image",
    "image/x-portable-pixmap": "Portable Pixmap Image",
    "image/x-raw": "Raw Image",
    "image/x-raw-adobe": "Adobe Digital Negative Image",
    "image/x-tga": "TGA Image",
    "image/x-wmf": "WMF Image",
    "image/x-xbitmap": "X Bitmap Graphic",
    "image/x-xfig": "XFIG Graphic",
    "image/xcf": "GIMP Image",
    "image/xpm": "X Pixmap Graphic",
    "message/delivery-status": "Delivery Status Notification",
    "message/rfc822": "Email Message",
    "message/x-emlx": "EMLX Email Message",
    "multipart/appledouble": "AppleDouble File",
    "special/any": "Any",
    "text/calendar": "iCalendar/vCalendar File",
    "text/css": "CSS Style Sheet",
    "text/csv": "Comma-separated Values File",
    "text/html": "HTML Document",
    "text/java": "Java Source File",
    "text/javascript": "JavaScript Source File",
    "text/plain": "Plain Text Document",
    "text/rdf+n3": "Notation 3 File",
    "text/rfc822-headers": "Email Headers",
    "text/tab-separated-values": "Tab-separated Values File",
    "text/vcard": "vCard File",
    "text/vnd.wap.wml": "Wireless Markup Language Document",
    "text/x-diff": "DIFF file",
    "text/x-plist": "Apple ASCII Property List",
    "video/3gpp": "3GPP Multimedia File",
    "video/3gpp2": "3GPP2 Multimedia File",
    "video/avi": "AVI Video Clip",
    "video/mj2": "Motion JPEG 2000",
    "video/mp4": "MPEG-4 Video File",
    "video/mpeg": "MPEG Video Clip",
    "video/quicktime": "QuickTime Video Clip",
    "video/quicktime+mp4": "QuickTime Video Clip (MPEG-4)",
    "video/vnd.dvb.file": "Digital Video Broadcasting (DVB) File",
    "video/webm": "WebM Video",
    "video/x-flv": "Flash Video File",
    "video/x-matroska": "Matroska Multimedia Container",
    "video/x-ms-asf": "Advanced Streaming Format Clip",
    "video/x-ms-asx": "Advanced Stream Redirector",
    "video/x-ms-wm": "Unknown Windows Media Clip",
    "video/x-ms-wmv": "Windows Media Video Clip",
    "video/x-ms-wmx": "Windows Media Player A/V Shortcut",
    "video/x-ms-wvx": "Windows Media Video Redirector"
}

OBSERVED = [
    "",
    "application/applefile",
    "application/arj",
    "application/bat",
    "application/binhex",
    "application/bzip",
    "application/bzip2",
    "application/compress",
    "application/doc",
    "application/gzip",
    "application/haansofthwp",
    "application/iff",
    "application/internet-shortcut",
    "application/java-archive",
    "application/java-vm",
    "application/javascript",
    "application/json",
    "application/mac-binhex",
    "application/mac-binhex40",
    "application/mbox",
    "application/mdb",
    "application/ms-powerpoint",
    "application/ms-tnef",
    "application/msaccess",
    "application/msexcel",
    "application/msexcell",
    "application/msonenote",
    "application/mspowerpnt",
    "application/mspowerpoint",
    "application/msproj",
    "application/msproject",
    "application/msword",
    "application/octet-stream",
    "application/ogg",
    "application/onenote",
    "application/owl+xml",
    "application/pcap",
    "application/pdf",
    "application/pgp-encrypted",
    "application/pgp-signature",
    "application/pkcs7-mime",
    "application/pkcs7-signature",
    "application/plist+xml",
    "application/postscript",
    "application/powerpoint",
    "application/presentations",
    "application/presentations-v3",
    "application/rdf+xml",
    "application/riff",
    "application/rsmf",
    "application/rtf",
    "application/stuffit",
    "application/stuffitx",
    "application/tar",
    "application/trix",
    "application/unix-v7-tar",
    "application/vnd-ms-powerpoint",
    "application/vnd.accessdata-ftk-ad1-disk-image",
    "application/vnd.adobe.air-application-installer-package+zip",
    "application/vnd.aff3-container",
    "application/vnd.aff4-container",
    "application/vnd.apple-safari-bookmark-db",
    "application/vnd.apple-safari-bookmark-entry",
    "application/vnd.apple-safari-bookmarks-plist",
    "application/vnd.apple-safari-history-db",
    "application/vnd.apple-safari-history-entry",
    "application/vnd.apple-safari-history-plist",
    "application/vnd.apple.keynote",
    "application/vnd.apple.numbers",
    "application/vnd.corel-draw",
    "application/vnd.debian.binary-package",
    "application/vnd.fdf",
    "application/vnd.framemaker",
    "application/vnd.google-chrome-bookmark-entry",
    "application/vnd.google-chrome-bookmarks",
    "application/vnd.google-chrome-cache-index-entry",
    "application/vnd.google-chrome-cache-index-file",
    "application/vnd.google-chrome-cookies",
    "application/vnd.google-chrome-cookies-entry",
    "application/vnd.google-chrome-formhistory",
    "application/vnd.google-chrome-formhistory-entry",
    "application/vnd.google-chrome-history",
    "application/vnd.google-chrome-history-download",
    "application/vnd.google-chrome-history-entry",
    "application/vnd.google-chrome-history-kwsearch",
    "application/vnd.google-chrome-logindata",
    "application/vnd.google-chrome-logindata-entry",
    "application/vnd.hancom.hwpx",
    "application/vnd.lotus-notes",
    "application/vnd.lotus-notes-deletion-stub",
    "application/vnd.lotus-notes-document",
    "application/vnd.mozilla-firefox-bookmark-entry",
    "application/vnd.mozilla-firefox-cookies",
    "application/vnd.mozilla-firefox-cookies-entry",
    "application/vnd.mozilla-firefox-formhistory",
    "application/vnd.mozilla-firefox-formhistory-entry",
    "application/vnd.mozilla-firefox-history",
    "application/vnd.mozilla-firefox-history-download",
    "application/vnd.mozilla-firefox-history-entry",
    "application/vnd.mozilla-firefox-input-entry",
    "application/vnd.ms-access",
    "application/vnd.ms-activex-form-control",
    "application/vnd.ms-binder",
    "application/vnd.ms-cab-compressed",
    "application/vnd.ms-chart",
    "application/vnd.ms-compound-file",
    "application/vnd.ms-edb",
    "application/vnd.ms-equation",
    "application/vnd.ms-ese",
    "application/vnd.ms-excel",
    "application/vnd.ms-excel.addin.macroenabled.12",
    "application/vnd.ms-excel.sheet.binary.macroenabled.12",
    "application/vnd.ms-excel.sheet.macroenabled.12",
    "application/vnd.ms-excel.template.macroenabled.12",
    "application/vnd.ms-excel.v2",
    "application/vnd.ms-excel.v3",
    "application/vnd.ms-excel.v4",
    "application/vnd.ms-exchange-edb",
    "application/vnd.ms-exchange-stm",
    "application/vnd.ms-ole2-container",
    "application/vnd.ms-outlook",
    "application/vnd.ms-outlook-note",
    "application/vnd.ms-outlook-pst",
    "application/vnd.ms-outlookexpress",
    "application/vnd.ms-pki.seccat",
    "application/vnd.ms-powerpoint",
    "application/vnd.ms-powerpoint.addin.macroenabled.12",
    "application/vnd.ms-powerpoint.presentation.macroenabled.12",
    "application/vnd.ms-powerpoint.slideshow.macroenabled.12",
    "application/vnd.ms-powerpoint.template.macroenabled.12",
    "application/vnd.ms-project",
    "application/vnd.ms-publisher",
    "application/vnd.ms-registry",
    "application/vnd.ms-registry-key",
    "application/vnd.ms-sdb",
    "application/vnd.ms-tnef",
    "application/vnd.ms-virtualpc-disk-image",
    "application/vnd.ms-virtualpc-disk-image-v2",
    "application/vnd.ms-visio.drawing.macroenabled.main+xml",
    "application/vnd.ms-visio.drawing.main+xml",
    "application/vnd.ms-visio.stencil.macroenabled.main+xml",
    "application/vnd.ms-visio.stencil.main+xml",
    "application/vnd.ms-visio.template.macroenabled.main+xml",
    "application/vnd.ms-visio.template.main+xml",
    "application/vnd.ms-windows-event-log",
    "application/vnd.ms-windows-ie-cookies-entry",
    "application/vnd.ms-windows-ie-recovery-store",
    "application/vnd.ms-windows-installer-package",
    "application/vnd.ms-windows-installer-patch",
    "application/vnd.ms-windows-installer-transform",
    "application/vnd.ms-windows-internet-bookmark",
    "application/vnd.ms-windows-internet-history-download",
    "application/vnd.ms-windows-internet-history-entry",
    "application/vnd.ms-windows-internet-typed-url",
    "application/vnd.ms-windows-search",
    "application/vnd.ms-windows-urlcache",
    "application/vnd.ms-windows-webcache",
    "application/vnd.ms-windows-xml-event-log",
    "application/vnd.ms-windows-xml-event-log-entry",
    "application/vnd.ms-word",
    "application/vnd.ms-word.document.macroenabled.12",
    "application/vnd.ms-word.template.macroenabled.12",
    "application/vnd.ms-works",
    "application/vnd.ms-xpsdocument",
    "application/vnd.msaccess",
    "application/vnd.mspowerpoint",
    "application/vnd.msword",
    "application/vnd.oasis.opendocument.base",
    "application/vnd.oasis.opendocument.chart",
    "application/vnd.oasis.opendocument.chart-template",
    "application/vnd.oasis.opendocument.database",
    "application/vnd.oasis.opendocument.formula",
    "application/vnd.oasis.opendocument.formula-template",
    "application/vnd.oasis.opendocument.graphics",
    "application/vnd.oasis.opendocument.graphics-template",
    "application/vnd.oasis.opendocument.image",
    "application/vnd.oasis.opendocument.image-template",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.presentation-template",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet-template",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.oasis.opendocument.text-master",
    "application/vnd.oasis.opendocument.text-template",
    "application/vnd.oasis.opendocument.text-web",
    "application/vnd.openxmlformats-officedocument",
    "application/vnd.openxmlformats-officedocument.presentationml",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    "application/vnd.openxmlformats-officedocument.presentationml.template",
    "application/vnd.openxmlformats-officedocument.spreadsheetml",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    "application/vnd.openxmlformats-officedocument.wordprocessingml",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "application/vnd.stardivision.calc",
    "application/vnd.stardivision.chart",
    "application/vnd.stardivision.draw",
    "application/vnd.stardivision.impress",
    "application/vnd.stardivision.impress-packed",
    "application/vnd.stardivision.mail",
    "application/vnd.stardivision.math",
    "application/vnd.stardivision.writer",
    "application/vnd.stardivision.writer-global",
    "application/vnd.sun.xml.base",
    "application/vnd.sun.xml.calc",
    "application/vnd.sun.xml.calc.template",
    "application/vnd.sun.xml.draw",
    "application/vnd.sun.xml.draw.template",
    "application/vnd.sun.xml.impress",
    "application/vnd.sun.xml.impress.template",
    "application/vnd.sun.xml.math",
    "application/vnd.sun.xml.writer",
    "application/vnd.sun.xml.writer.template",
    "application/vnd.tcpdump.pcap",
    "application/vnd.visio",
    "application/vnd.vmware-vmdk-disk-image",
    "application/vnd.vound.folder",
    "application/vnd.vound.symlink",
    "application/vnd.wordperfect",
    "application/wb2",
    "application/winhlp",
    "application/winword",
    "application/wmf",
    "application/word",
    "application/wps-office.dps",
    "application/wps-office.dpt",
    "application/wps-office.et",
    "application/wps-office.ett",
    "application/wps-office.wps",
    "application/wps-office.wpt",
    "application/x-123",
    "application/x-7z-compressed",
    "application/x-adobe-indesign",
    "application/x-alz",
    "application/x-alz-compressed",
    "application/x-apple-account-database",
    "application/x-apple-address-book-database",
    "application/x-apple-calendar-database",
    "application/x-apple-call-history-database",
    "application/x-apple-notes-database",
    "application/x-applescript",
    "application/x-arj",
    "application/x-axcrypt",
    "application/x-bash",
    "application/x-bitcoin-blockchain",
    "application/x-bitcoin-wallet",
    "application/x-bitlocker-image",
    "application/x-bitlocker-togo-image",
    "application/x-bplist",
    "application/x-bzip",
    "application/x-bzip2",
    "application/x-compress",
    "application/x-cpio",
    "application/x-csh",
    "application/x-deb",
    "application/x-debian-package",
    "application/x-dogecoin-blockchain",
    "application/x-dogecoin-wallet",
    "application/x-dos_ms_excel",
    "application/x-emlxpart",
    "application/x-empty",
    "application/x-encase-ewf-image",
    "application/x-encase-ewf-image-v2",
    "application/x-encase-logical-image",
    "application/x-encase-logical-image-v2",
    "application/x-excel",
    "application/x-font-otf",
    "application/x-font-ttf",
    "application/x-foxmail",
    "application/x-framemaker",
    "application/x-gtar",
    "application/x-gzip",
    "application/x-harvard-graphics",
    "application/x-hwp",
    "application/x-hwp-v3",
    "application/x-iff",
    "application/x-imessage-db",
    "application/x-installshield-compressedfile",
    "application/x-intella-activity",
    "application/x-intella-aff-disk-image",
    "application/x-intella-android-conversation-xml",
    "application/x-intella-android-logical-acquisition",
    "application/x-intella-apfs-partition",
    "application/x-intella-app-account",
    "application/x-intella-app-usage",
    "application/x-intella-apple-dmg-compressed-image",
    "application/x-intella-apple-dmg-encrypted-v1-image",
    "application/x-intella-apple-dmg-encrypted-v2-image",
    "application/x-intella-apple-dmg-image",
    "application/x-intella-apple-mail",
    "application/x-intella-autofill-entry",
    "application/x-intella-automatic-jump-list",
    "application/x-intella-aws-s3-account",
    "application/x-intella-aws-s3-bucket",
    "application/x-intella-bam-cache-entry",
    "application/x-intella-blackberry-message",
    "application/x-intella-bloomberg-conversation-xml",
    "application/x-intella-bloomberg-plain-text-dump",
    "application/x-intella-bloomberg-xml-dump",
    "application/x-intella-bluetooth-connection",
    "application/x-intella-bookmark",
    "application/x-intella-boot-sector-file",
    "application/x-intella-browser-cache",
    "application/x-intella-calendar-entry",
    "application/x-intella-carved-string",
    "application/x-intella-cell-connection",
    "application/x-intella-cellebrite-conversation-xml",
    "application/x-intella-cellebrite-file",
    "application/x-intella-cellebrite-ufdr-report-file",
    "application/x-intella-cellebrite-xml-report-file",
    "application/x-intella-cellphone-contact",
    "application/x-intella-cellphone-event",
    "application/x-intella-cellphone-generic-social-media-activity",
    "application/x-intella-cellphone-recording",
    "application/x-intella-cellphone-report",
    "application/x-intella-chat-message",
    "application/x-intella-chat-message-xml",
    "application/x-intella-chat-message-xml-reaction",
    "application/x-intella-comm-stat-entry",
    "application/x-intella-contact",
    "application/x-intella-conversation",
    "application/x-intella-conversation-event",
    "application/x-intella-conversation-root",
    "application/x-intella-cookie",
    "application/x-intella-custom-jump-list",
    "application/x-intella-dd-disk-image",
    "application/x-intella-device-acquisition",
    "application/x-intella-dictionary-word",
    "application/x-intella-dropbox-account",
    "application/x-intella-exfat-partition",
    "application/x-intella-fat16-partition",
    "application/x-intella-fax",
    "application/x-intella-file-message",
    "application/x-intella-for-mac-olk14-mailbox",
    "application/x-intella-for-mac-olk15-mailbox",
    "application/x-intella-gmail-account",
    "application/x-intella-google-account",
    "application/x-intella-google-calendar",
    "application/x-intella-google-chat",
    "application/x-intella-google-chat-conversation-xml",
    "application/x-intella-google-chat-space",
    "application/x-intella-google-contacts",
    "application/x-intella-google-drive",
    "application/x-intella-google-gmail",
    "application/x-intella-google-meet",
    "application/x-intella-google-meet-conference",
    "application/x-intella-google-meet-participant-session",
    "application/x-intella-google-takeout-export",
    "application/x-intella-gps-location",
    "application/x-intella-gpt-partition",
    "application/x-intella-hfs-partition",
    "application/x-intella-history-entry",
    "application/x-intella-hotmail-dump",
    "application/x-intella-icloud-account",
    "application/x-intella-icloud-device",
    "application/x-intella-imap-connection",
    "application/x-intella-imessage-conversation-xml",
    "application/x-intella-installed-application",
    "application/x-intella-iphone-message",
    "application/x-intella-itunes-backup",
    "application/x-intella-itunes-backup-iphone-info",
    "application/x-intella-itunes-backup-voicemail",
    "application/x-intella-itunes-conversation-xml",
    "application/x-intella-itunes-encrypted-backup",
    "application/x-intella-journey",
    "application/x-intella-key-evidence",
    "application/x-intella-keyboard-cache",
    "application/x-intella-load-file",
    "application/x-intella-local-disk",
    "application/x-intella-log-entry",
    "application/x-intella-mbr-partition",
    "application/x-intella-message-status-update",
    "application/x-intella-mms-message",
    "application/x-intella-ms-teams-account",
    "application/x-intella-ms-teams-channel",
    "application/x-intella-ms-teams-conversation",
    "application/x-intella-ms-teams-conversation-xml",
    "application/x-intella-ms-teams-message",
    "application/x-intella-net-adapter",
    "application/x-intella-net-connection",
    "application/x-intella-note",
    "application/x-intella-notification",
    "application/x-intella-office365-account",
    "application/x-intella-office365-connection",
    "application/x-intella-olk14category",
    "application/x-intella-olk14contacts",
    "application/x-intella-olk14dbheader",
    "application/x-intella-olk14event",
    "application/x-intella-olk14folder",
    "application/x-intella-olk14message",
    "application/x-intella-olk14msgattachment",
    "application/x-intella-olk14msgsource",
    "application/x-intella-olk14note",
    "application/x-intella-olk14preferences",
    "application/x-intella-olk14recent",
    "application/x-intella-olk14schedule",
    "application/x-intella-olk14search",
    "application/x-intella-olk14signatures",
    "application/x-intella-olk15",
    "application/x-intella-olk15calattachment",
    "application/x-intella-olk15category",
    "application/x-intella-olk15contact",
    "application/x-intella-olk15event",
    "application/x-intella-olk15fold",
    "application/x-intella-olk15folder",
    "application/x-intella-olk15image",
    "application/x-intella-olk15imapsyncmap",
    "application/x-intella-olk15mailaccount",
    "application/x-intella-olk15main",
    "application/x-intella-olk15message",
    "application/x-intella-olk15msgattachment",
    "application/x-intella-olk15msgsource",
    "application/x-intella-olk15note",
    "application/x-intella-olk15recentaddresses",
    "application/x-intella-olk15search",
    "application/x-intella-olk15signature",
    "application/x-intella-olk15task",
    "application/x-intella-onedrive-account",
    "application/x-intella-operating-system-information",
    "application/x-intella-outlook-account",
    "application/x-intella-outlook-distribution-list",
    "application/x-intella-outlook-for-mac",
    "application/x-intella-outlook-ipm-DistList",
    "application/x-intella-outlook-ipm-SkypeTeams-Message",
    "application/x-intella-outlook-sharing-message",
    "application/x-intella-oxygen-conversation-xml",
    "application/x-intella-oxygen-file",
    "application/x-intella-oxygen-xml-report-file",
    "application/x-intella-packet-data",
    "application/x-intella-password",
    "application/x-intella-phone-call",
    "application/x-intella-phone-conversation",
    "application/x-intella-pidgin-accounts-file",
    "application/x-intella-pidgin-html-conversation",
    "application/x-intella-pidgin-html-conversation-xml",
    "application/x-intella-pidgin-html-dump",
    "application/x-intella-pidgin-plain-text-conversation",
    "application/x-intella-pidgin-plain-text-conversation-xml",
    "application/x-intella-pidgin-plain-text-dump",
    "application/x-intella-powering-event",
    "application/x-intella-prefetch-file",
    "application/x-intella-prefetch-file-entry",
    "application/x-intella-raw-disk",
    "application/x-intella-recent-apps-entry",
    "application/x-intella-recent-items-entry",
    "application/x-intella-recently-used-file",
    "application/x-intella-rsmf-conversation-xml",
    "application/x-intella-rss-feed",
    "application/x-intella-run-mru-entry",
    "application/x-intella-sametime-dump",
    "application/x-intella-sametime-dump-xml",
    "application/x-intella-search-entry",
    "application/x-intella-sharepoint-account",
    "application/x-intella-sharepoint-discussion-board",
    "application/x-intella-sharepoint-doc-library",
    "application/x-intella-sharepoint-newsfeed",
    "application/x-intella-sharepoint-post",
    "application/x-intella-sharepoint-site",
    "application/x-intella-skype-conversation",
    "application/x-intella-skype-conversation-xml",
    "application/x-intella-skype-message",
    "application/x-intella-slack",
    "application/x-intella-slack-activity-log",
    "application/x-intella-slack-conversation",
    "application/x-intella-slack-conversation-thread",
    "application/x-intella-slack-conversation-xml",
    "application/x-intella-slack-conversations",
    "application/x-intella-slack-direct-m-channel",
    "application/x-intella-slack-entry",
    "application/x-intella-slack-file",
    "application/x-intella-slack-group-m-channel",
    "application/x-intella-slack-log",
    "application/x-intella-slack-message",
    "application/x-intella-slack-mp-direct-m-channel",
    "application/x-intella-slack-public-channel",
    "application/x-intella-sms-message",
    "application/x-intella-speed-dial",
    "application/x-intella-sqlite-table-records",
    "application/x-intella-startup-program",
    "application/x-intella-task",
    "application/x-intella-task-request",
    "application/x-intella-time-zone-information",
    "application/x-intella-timeline-entry",
    "application/x-intella-unknown-cellphone-item",
    "application/x-intella-usb-storage-device",
    "application/x-intella-user-account",
    "application/x-intella-user-account-login",
    "application/x-intella-user-account-logout",
    "application/x-intella-user-assist",
    "application/x-intella-voicemail",
    "application/x-intella-w4-case",
    "application/x-intella-web-browser-download",
    "application/x-intella-whatsapp-conversation-xml",
    "application/x-intella-wifi-connection",
    "application/x-intella-windows-10-timeline-db",
    "application/x-intella-windows-10-timeline-entry",
    "application/x-intella-windows-push-notification-db",
    "application/x-intella-windows-push-notification-entry",
    "application/x-intella-windows-registry-artifacts",
    "application/x-intella-windows-shellbag",
    "application/x-intella-windows10mail-backup",
    "application/x-intella-xry-conversation-xml",
    "application/x-intella-xry-file",
    "application/x-intella-xry-xml-report-file",
    "application/x-intella-xwfs2-disk",
    "application/x-iso-base-media",
    "application/x-iso9660-image",
    "application/x-java-class",
    "application/x-java-enterprisearchive",
    "application/x-java-webarchive",
    "application/x-ksh",
    "application/x-litecoin-blockchain",
    "application/x-lotus-notes",
    "application/x-md5",
    "application/x-mdb",
    "application/x-microsoft-rpmsg-message",
    "application/x-mimearchive",
    "application/x-ms-dos-executable",
    "application/x-ms-excel",
    "application/x-ms-project",
    "application/x-ms-scr",
    "application/x-ms-shortcut",
    "application/x-ms-wmz",
    "application/x-msaccess",
    "application/x-msbinder",
    "application/x-msdownload",
    "application/x-msexcel",
    "application/x-msg",
    "application/x-msmetafile",
    "application/x-mspowerpoint",
    "application/x-msproject",
    "application/x-msw6",
    "application/x-msword",
    "application/x-multibit-blockchain",
    "application/x-multibit-classic-wallet",
    "application/x-multibit-hd-wallet",
    "application/x-pdf",
    "application/x-pkcs7-signature",
    "application/x-powerpoint",
    "application/x-quattropro",
    "application/x-rar-compressed",
    "application/x-rar-compressed-v5",
    "application/x-redhat-package-manager",
    "application/x-sh",
    "application/x-sha",
    "application/x-shockwave-flash",
    "application/x-sicky-notes-db",
    "application/x-sicky-notes-message",
    "application/x-sit",
    "application/x-sitx",
    "application/x-slk",
    "application/x-sqlite2",
    "application/x-sqlite3",
    "application/x-sqlite3-skype",
    "application/x-sqlite3-skype-11x-12x",
    "application/x-sqlite3-skype-14x",
    "application/x-sqlite3-skype-8x",
    "application/x-stuffit",
    "application/x-stuffitx",
    "application/x-tar",
    "application/x-tsh",
    "application/x-turtle",
    "application/x-url",
    "application/x-vnd.corel.zcf.draw.document+zip",
    "application/x-webarchive",
    "application/x-whatsapp-db",
    "application/x-wim",
    "application/x-wmf",
    "application/x-xls",
    "application/x-xz",
    "application/x-zip-compressed",
    "application/xhtml+xml",
    "application/xls",
    "application/xml",
    "application/xslt+xml",
    "application/zip",
    "application/zst",
    "audio/3gpp",
    "audio/3gpp2",
    "audio/8svx",
    "audio/aiff",
    "audio/amr",
    "audio/amr-wb",
    "audio/flac",
    "audio/midi",
    "audio/midi+riff",
    "audio/mp3",
    "audio/mp4",
    "audio/mpeg",
    "audio/mpeg3",
    "audio/mpg",
    "audio/vnd.wave",
    "audio/wav",
    "audio/wave",
    "audio/x-8svx",
    "audio/x-aifc",
    "audio/x-aiff",
    "audio/x-flac",
    "audio/x-m4a",
    "audio/x-matroska",
    "audio/x-midi",
    "audio/x-mp3",
    "audio/x-mpeg",
    "audio/x-mpeg3",
    "audio/x-mpegaudio",
    "audio/x-mpg",
    "audio/x-ms-wax",
    "audio/x-ms-wma",
    "audio/x-wav",
    "category/accounts",
    "category/apple_plist",
    "category/archives",
    "category/audio",
    "category/aws-s3",
    "category/browser_bookmarks",
    "category/browser_cookies",
    "category/browser_downloads",
    "category/browser_form_history",
    "category/browser_history",
    "category/browser_logins",
    "category/cell_phone",
    "category/chat",
    "category/chat_conversations",
    "category/chat_messages",
    "category/cloud_service",
    "category/communication",
    "category/contacts",
    "category/containers",
    "category/corel_draw",
    "category/crypto_currency",
    "category/databases",
    "category/disk_images",
    "category/documents",
    "category/dropbox",
    "category/email",
    "category/email_containers",
    "category/email_messages",
    "category/executables",
    "category/forensic_containers",
    "category/formulas",
    "category/gmail",
    "category/google",
    "category/graphics",
    "category/hangul_document",
    "category/icloud",
    "category/images",
    "category/java_archives",
    "category/launched_programs",
    "category/media",
    "category/microsoft_excel",
    "category/microsoft_powerpoint",
    "category/microsoft_visio",
    "category/microsoft_word",
    "category/office365",
    "category/office_openxml_excel",
    "category/office_openxml_powerpoint",
    "category/office_openxml_word",
    "category/olk14",
    "category/olk15",
    "category/other_communications",
    "category/other_documents",
    "category/other_media",
    "category/others",
    "category/phoneBackups",
    "category/pidgin_chat",
    "category/presentations",
    "category/rar_archives",
    "category/recently_accessed_files",
    "category/root",
    "category/scheduling",
    "category/security_and_integrity",
    "category/sharepoint",
    "category/source_code",
    "category/spreadsheets",
    "category/sqlite",
    "category/system",
    "category/tar_archives",
    "category/unix_shell_scripts",
    "category/unknown",
    "category/user_activity",
    "category/user_sessions",
    "category/video",
    "category/voice",
    "category/windows_registry",
    "category/word_processing",
    "category/wrappers",
    "category/www",
    "image/bmp",
    "image/cgm",
    "image/dng",
    "image/gif",
    "image/heic",
    "image/heic-sequence",
    "image/heif",
    "image/heif-sequence",
    "image/icns",
    "image/iff",
    "image/ilbm",
    "image/jbig2",
    "image/jp2",
    "image/jpeg",
    "image/jpeg2000",
    "image/jpeg2000-codestream",
    "image/jpg",
    "image/jpm",
    "image/jpx",
    "image/notesbitmap",
    "image/pict",
    "image/png",
    "image/svg+xml",
    "image/tiff",
    "image/vnd.adobe.photoshop",
    "image/vnd.djvu",
    "image/vnd.microsoft.icon",
    "image/vnd.ms-modi",
    "image/vnd.radiance",
    "image/vnd.zbrush.pcx",
    "image/webp",
    "image/wmf",
    "image/x-djvu",
    "image/x-dwf",
    "image/x-dwg",
    "image/x-dxf",
    "image/x-emf",
    "image/x-icon",
    "image/x-iff",
    "image/x-ilbm",
    "image/x-itunes-albumartwork",
    "image/x-jbig2",
    "image/x-paintshoppro",
    "image/x-pcx",
    "image/x-pict",
    "image/x-png",
    "image/x-portable-bitmap",
    "image/x-portable-greymap",
    "image/x-portable-pixmap",
    "image/x-raw",
    "image/x-raw-adobe",
    "image/x-tga",
    "image/x-win-metafile",
    "image/x-wmf",
    "image/x-xbitmap",
    "image/x-xfig",
    "image/xcf",
    "image/xpm",
    "message/delivery-status",
    "message/news",
    "message/rfc822",
    "message/rfc822-headers",
    "message/x-emlx",
    "multipart/appledouble",
    "special/any",
    "text/calendar",
    "text/css",
    "text/csv",
    "text/html",
    "text/java",
    "text/javascript",
    "text/plain",
    "text/rdf+n3",
    "text/rfc822-headers",
    "text/rtf",
    "text/tab-separated-values",
    "text/url",
    "text/vcard",
    "text/vnd.wap.wml",
    "text/x-diff",
    "text/x-plist",
    "text/x-url",
    "text/x-vcard",
    "text/xml",
    "video/3gpp",
    "video/3gpp2",
    "video/avi",
    "video/dvd",
    "video/mj2",
    "video/mp4",
    "video/mpeg",
    "video/msvideo",
    "video/quicktime",
    "video/quicktime+mp4",
    "video/vnd.avi",
    "video/vnd.dvb.file",
    "video/webm",
    "video/x-flv",
    "video/x-m4v",
    "video/x-matroska",
    "video/x-matroska-3d",
    "video/x-ms-asf",
    "video/x-ms-asx",
    "video/x-ms-wm",
    "video/x-ms-wmv",
    "video/x-ms-wmx",
    "video/x-ms-wvx",
    "video/x-msvideo",
    "wwwserver/redirection",
    "zz-application/zz-winassoc-doc",
    "zz-application/zz-winassoc-xls"
]
